### PR TITLE
Changed behaviour (see comment)

### PR DESCRIPTION
**Pull request by TheOnAndOnlyZenomat**
Added the feature, that you can specify your own Wallpaperfolder, no need for specific naming of the folder. Because of this the first point in the README was obsolete and I therefore deleted it. Furthermore I fixed a formating issue in the myprimcolors.txt, because of whom I wasn't able to run the script. Also added feh as a wallpaper setter

### CODE REVIEW

**Comment by BogdanTheGeek** [comment]
Please fix the issues commented on the commits and squash all of the commits into one.

**Comment by TheOnAndOnlyZenomat** [comment]
> Please fix the issues commented on the commits and squash all of the commits into one.

Yeah, how exactly do I squish them (this is my first time using contributing on github to another project)?

**Comment by BogdanTheGeek** [comment]
https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by TheOnAndOnlyZenomat** [comment]
I think I got it now

**Comment by BogdanTheGeek** [comment]
Why did you remove esac from chwall?

**Comment by TheOnAndOnlyZenomat** [comment]
I did... Was on accident. Maybe I am just stupid or this process is utterly complicated :D

**Review by BogdanTheGeek — APPROVED** [review]

**Comment by TheOnAndOnlyZenomat** [comment]
Did it all work out now?

**Comment by BogdanTheGeek** [comment]
Yeah, i thinks its all good for now. Let me know if it works out ok for you.
Thanks for your contribution.

**Comment by TheOnAndOnlyZenomat** [comment]
> Let me know if it works out ok for you

Yep, everything works on my end

> Thanks for your contribution.

My pleasure

**Pull request merged**
